version: '3'
services:
        web:
                image: flask_8332_v1
                build: .
                ports:
                        - "8332:8332"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
